SET FOREIGN_KEY_CHECKS = 0;
CREATE DATABASE ELIXIR CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ELIXIR;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE CLIENT_ (
	ID_CLIENT INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NOM_CLIENT VARCHAR(50) NOT NULL,
	PRENOM_CLIENT VARCHAR(50) NOT NULL,
	ADRESSE_CLIENT VARCHAR(50) NOT NULL,
	EMAIL_CLIENT VARCHAR(50) UNIQUE NOT NULL,
	TELEPHONE_CLIENT VARCHAR(20) NOT NULL,
	DATE_NAISSANCE DATE,
	DATE_INSCRIPTION DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE MAGASIN (
    ID_MAGASIN INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOM_MAGASIN VARCHAR(50) UNIQUE NOT NULL,
    ADRESSE_MAGASIN VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
    
 CREATE TABLE EMPLOYE (
    ID_EMPLOYE INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOM_EMPLOYE VARCHAR(50) NOT NULL,
    PRENOM_EMPLOYE VARCHAR(50) NOT NULL,
    POSTE VARCHAR(50) NOT NULL,
    SALAIRE DECIMAL(15, 2) NOT NULL,
	ID_EMPLOYE_MANAGER INT UNSIGNED NULL,
    ID_MAGASIN INT UNSIGNED NULL,

    CONSTRAINT FK_EMPLOYE_MANAGER FOREIGN KEY (ID_EMPLOYE_MANAGER) REFERENCES EMPLOYE (ID_EMPLOYE) ON DELETE SET NULL,
    CONSTRAINT FK_EMPLOYE_MAGASIN FOREIGN KEY (ID_MAGASIN) REFERENCES MAGASIN (ID_MAGASIN) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PARFUM (
    ID_PARFUM INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOM_PARFUM VARCHAR(50) NOT NULL,
    CATEGORIE VARCHAR(50) NOT NULL,
    GENRE VARCHAR(50) NOT NULL,
    PRIX DECIMAL(15, 2) NOT NULL,
    DESCRIPTION_ VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE FOURNISSEUR (
    ID_FOURNISSEUR INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
    NOM_FOURNISSEUR VARCHAR(100) UNIQUE NOT NULL,
    ADRESSE_FOURNISSEUR VARCHAR(150) NOT NULL,
    TELEPHONE_FOURNISSEUR VARCHAR(20) NOT NULL,
    EMAIL_FOURNISSEUR VARCHAR(50) UNIQUE NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
    
CREATE TABLE PROMOTION (
    ID_PROMOTION INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TYPE_PROMO VARCHAR(50) NOT NULL,
    DATE_DEBUT DATE ,
    DATE_FIN DATE,
    TAUX_REDUCTION DECIMAL(5, 2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE OPERATION (
    ID_OPERATION INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TYPE_OPERATION VARCHAR(50) NOT NULL,
    QUANTITE INT NOT NULL,
    DATE_OPERATION DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE STOCK (
    ID_PARFUM INT UNSIGNED,
    ID_MAGASIN INT UNSIGNED,
    ID_OPERATION INT UNSIGNED,
    QUANTITE INT,
    PRIMARY KEY (ID_PARFUM, ID_MAGASIN, ID_OPERATION),
    
    CONSTRAINT FK_STOCK_PARFUM FOREIGN KEY (ID_PARFUM) REFERENCES PARFUM (ID_PARFUM) ON DELETE CASCADE,
    CONSTRAINT FK_STOCK_MAGASIN FOREIGN KEY (ID_MAGASIN) REFERENCES MAGASIN (ID_MAGASIN) ON DELETE CASCADE,
    CONSTRAINT FK_STOCK_OPERATION FOREIGN KEY (ID_OPERATION) REFERENCES OPERATION (ID_OPERATION) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PROPOSE (
    ID_PARFUM INT UNSIGNED NOT NULL,
    ID_FOURNISSEUR INT UNSIGNED NOT NULL,
    PRIX_FOURNISSEUR DECIMAL(15, 2) NOT NULL,
    PRIMARY KEY (ID_PARFUM, ID_FOURNISSEUR ),
    
    CONSTRAINT FK_PROPOSE_PARFUM FOREIGN KEY (ID_PARFUM) REFERENCES PARFUM (ID_PARFUM) ON DELETE CASCADE,
    CONSTRAINT FK_PROPOSE_FOURNISSEUR FOREIGN KEY (ID_FOURNISSEUR) REFERENCES FOURNISSEUR (ID_FOURNISSEUR) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
    
CREATE TABLE AFFECTER (
    ID_PARFUM INT UNSIGNED NOT NULL,
    ID_PROMOTION INT UNSIGNED NOT NULL,
    PRIMARY KEY (ID_PARFUM, ID_PROMOTION),
    
    CONSTRAINT FK_AFFECTER_PARFUM FOREIGN KEY (ID_PARFUM) REFERENCES PARFUM (ID_PARFUM) ON DELETE CASCADE,
    CONSTRAINT FK_AFFECTER_PROMOTION FOREIGN KEY (ID_PROMOTION) REFERENCES PROMOTION (ID_PROMOTION) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE COMMANDE (
	ID_COMMANDE INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	DATE_COMMANDE DATETIME DEFAULT CURRENT_TIMESTAMP,
	CANAL VARCHAR(50) NOT NULL, 
	MONTANT_TOTAL DECIMAL(15, 2) DEFAULT 0,
	ID_CLIENT INT UNSIGNED NOT NULL,

	CONSTRAINT FK_COMMANDE_CLIENT_ FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT_ (ID_CLIENT) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
    
CREATE TABLE DETAILS_COMMANDE (
	ID_COMMANDE INT UNSIGNED NOT NULL,
	ID_PARFUM INT UNSIGNED NOT NULL,
	QUANTITE INT UNSIGNED NOT NULL,
	PRIX_UNITAIRE DECIMAL(10, 2) NOT NULL,
	PRIMARY KEY (ID_COMMANDE, ID_PARFUM),
    
	CONSTRAINT FK_DETAILS_COMMANDE_COMMANDE FOREIGN KEY (ID_COMMANDE) REFERENCES COMMANDE (ID_COMMANDE) ON DELETE CASCADE,
	CONSTRAINT FK_DETAILS_COMMANDE_PARFUM FOREIGN KEY (ID_PARFUM) REFERENCES PARFUM (ID_PARFUM) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
    
CREATE TABLE ACHAT_FOURNISSEUR (
	ID_ACHAT INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	DATE_ACHAT DATE NOT NULL,
	MONTANT_TOTAL DECIMAL(15, 2) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
     
CREATE TABLE ACHAT_DETAIL (
	ID_ACHAT INT UNSIGNED NOT NULL,
	ID_FOURNISSEUR INT UNSIGNED NOT NULL,
	PRIMARY KEY (ID_ACHAT, ID_FOURNISSEUR),
        
	CONSTRAINT FK_ACHATDETAIL_ACHAT FOREIGN KEY (ID_ACHAT) REFERENCES ACHAT_FOURNISSEUR (ID_ACHAT) ON DELETE CASCADE,
	CONSTRAINT FK_ACHATDETAIL_FOURNISSEUR FOREIGN KEY (ID_FOURNISSEUR) REFERENCES FOURNISSEUR (ID_FOURNISSEUR) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE ACHAT_DETAIL ADD COLUMN MONTANT INT;
